### ISSUE TITLE
[Bug] Date picker bug red text when just dragged

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/quickmock#608]
Components >> DatePicker

The Date Picker control has some date validaty checkup (and if fails it displays a red label), but... whenever you just drag and drop the control you get the red text, something like:

![Captura de pantalla 2024-12-09 a las 19 55 56](https://github.com/user-attachments/assets/fcd6b146-c5df-479c-826b-260a503ddb4d)

When you just drag and drop the picker it should be shown

**Comment by jsanzdev** [comment]
@brauliodiez 

The bug is not the validator, there is duplicated text on the picker. 

src/common/components/mock-components/front-components/datepickerinput-shape.tsx
<img width="451" alt="image" src="https://github.com/user-attachments/assets/82a828d0-21be-4937-9616-2b52c74d6929" />

Do we want to implement a validator for the date or just remove the text?
